sudo: false
env:
  global:
    - CC_TEST_REPORTER_ID=4f3ec44c8cb12d2b87fd85a92e04928698ce5eb8b8cb9f8802cf7bea4160b690
language: ruby
rvm:
  - 2.4.0
  - 2.4.1
  - 2.4.2
before_install: gem install bundler -v 1.15.4
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT