# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{anodator}
  s.version = "0.0.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tetsuhisa MAKINO"]
  s.date = %q{2015-08-10}
  s.description = %q{anodator is Anonymous Data Validator.}
  s.email = %q{tim.makino at gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.ja.rdoc",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.ja.rdoc",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "anodator.gemspec",
    "example/example_01.rb",
    "lib/anodator.rb",
    "lib/anodator/anodator_error.rb",
    "lib/anodator/check_result.rb",
    "lib/anodator/checker.rb",
    "lib/anodator/input_spec.rb",
    "lib/anodator/input_spec_item.rb",
    "lib/anodator/message.rb",
    "lib/anodator/output_spec.rb",
    "lib/anodator/rule.rb",
    "lib/anodator/rule_set.rb",
    "lib/anodator/utils.rb",
    "lib/anodator/validator.rb",
    "lib/anodator/validator/base.rb",
    "lib/anodator/validator/blank_validator.rb",
    "lib/anodator/validator/complex_validator.rb",
    "lib/anodator/validator/configuration_error.rb",
    "lib/anodator/validator/date_validator.rb",
    "lib/anodator/validator/format_validator.rb",
    "lib/anodator/validator/inclusion_validator.rb",
    "lib/anodator/validator/length_validator.rb",
    "lib/anodator/validator/numeric_validator.rb",
    "lib/anodator/validator/presence_validator.rb",
    "lib/anodator/validator/value_proxy.rb",
    "spec/anodator/check_result_spec.rb",
    "spec/anodator/checker_spec.rb",
    "spec/anodator/input_spec_item_spec.rb",
    "spec/anodator/input_spec_spec.rb",
    "spec/anodator/message_spec.rb",
    "spec/anodator/output_spec_spec.rb",
    "spec/anodator/rule_set_spec.rb",
    "spec/anodator/rule_spec.rb",
    "spec/anodator/utils_spec.rb",
    "spec/anodator/validator/base_spec.rb",
    "spec/anodator/validator/blank_validator_spec.rb",
    "spec/anodator/validator/complex_validator_spec.rb",
    "spec/anodator/validator/date_validator_spec.rb",
    "spec/anodator/validator/format_validator_spec.rb",
    "spec/anodator/validator/inclusion_validator_spec.rb",
    "spec/anodator/validator/length_validator_spec.rb",
    "spec/anodator/validator/numeric_validator_spec.rb",
    "spec/anodator/validator/presence_validator_spec.rb",
    "spec/anodator/validator_spec.rb",
    "spec/anodator_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{https://github.com/maki-tetsu/anodator}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{anodator is Anonymous Data Validator.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<rake>, ["= 0.8.7"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<rake>, ["= 0.8.7"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<rake>, ["= 0.8.7"])
  end
end

